// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/selected_currency/repository.go

// Package mock_selected_currency is a generated GoMock package.
package mock_selected_currency

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "gitlab.ozon.dev/paksergey94/telegram-bot/internal/model"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetSelectedCurrency mocks base method.
func (m *MockRepository) GetSelectedCurrency(ctx context.Context, userId int64) (*model.SelectedCurrency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSelectedCurrency", ctx, userId)
	ret0, _ := ret[0].(*model.SelectedCurrency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSelectedCurrency indicates an expected call of GetSelectedCurrency.
func (mr *MockRepositoryMockRecorder) GetSelectedCurrency(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSelectedCurrency", reflect.TypeOf((*MockRepository)(nil).GetSelectedCurrency), ctx, userId)
}

// SaveSelectedCurrency mocks base method.
func (m *MockRepository) SaveSelectedCurrency(ctx context.Context, currency string, userId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSelectedCurrency", ctx, currency, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSelectedCurrency indicates an expected call of SaveSelectedCurrency.
func (mr *MockRepositoryMockRecorder) SaveSelectedCurrency(ctx, currency, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSelectedCurrency", reflect.TypeOf((*MockRepository)(nil).SaveSelectedCurrency), ctx, currency, userId)
}
