// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/currency_rate/repository.go

// Package mock_currency_rate is a generated GoMock package.
package mock_currency_rate

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "gitlab.ozon.dev/paksergey94/telegram-bot/internal/model"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetRateByCurrency mocks base method.
func (m *MockRepository) GetRateByCurrency(currency string) (model.CurrencyRate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRateByCurrency", currency)
	ret0, _ := ret[0].(model.CurrencyRate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRateByCurrency indicates an expected call of GetRateByCurrency.
func (mr *MockRepositoryMockRecorder) GetRateByCurrency(currency interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRateByCurrency", reflect.TypeOf((*MockRepository)(nil).GetRateByCurrency), currency)
}

// SaveRate mocks base method.
func (m *MockRepository) SaveRate(name string, value float64) (model.CurrencyRate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRate", name, value)
	ret0, _ := ret[0].(model.CurrencyRate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveRate indicates an expected call of SaveRate.
func (mr *MockRepositoryMockRecorder) SaveRate(name, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRate", reflect.TypeOf((*MockRepository)(nil).SaveRate), name, value)
}
